### ISSUE TITLE
"gerablog --generate ." encounter error

### ISSUE THREAD

**Issue by luckypoem** [paulohrpinheiro/gerablog#1]
hi.

root@AR:/usr/local/gerablog-site# gerablog --generate .
/usr/local/rvm/gems/ruby-2.3.0/gems/parseconfig-1.0.8/lib/parseconfig.rb:58:in `each': Is a directory @ io_fillbuf - fd:7 . (Errno::EISDIR)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/parseconfig-1.0.8/lib/parseconfig.rb:58:in `each_with_index'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/parseconfig-1.0.8/lib/parseconfig.rb:58:in `block in import_config'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/parseconfig-1.0.8/lib/parseconfig.rb:58:in `open'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/parseconfig-1.0.8/lib/parseconfig.rb:58:in `import_config'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/parseconfig-1.0.8/lib/parseconfig.rb:40:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/gerablog-0.1.0/lib/gerablog/blog.rb:74:in `new'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/gerablog-0.1.0/lib/gerablog/blog.rb:74:in `load_config'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/gerablog-0.1.0/bin/gerablog:33:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/gerablog:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/gerablog:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
root@AR:/usr/local/gerablog-site#

how to fix it?
thank you!

**Comment by paulohrpinheiro** [comment]
Sorry for the delay, I guess I lost my first user, but the error occurred because the parameter should be a directory that will be created, not an existing one.

Something like (assuming `/usr/local/new-gerablog-site` does not exist): should work:

```
gerablog --generate /usr/local/new-gerablog-site
```

Thank you!
